using System;
using ListaEstruturaDeDecisao;
//Exercicio01.Main(args);
//Exercicio02.Main(args);
//Exercicio03.Main(args);
//Exercicio04.Main(args);
//Exercicio05.Main(args); 
//Exercicio06.Main(args); 
//Exercicio07.Main(args); 
//Exercicio08.Main(args); 
//Exercicio09.Main(args); 
//Exercicio10.Main(args); 
//Exercicio11.Main(args);
//Exercicio12.Main(args);
//Exercicio13.Main(args);
//Exercicio14.Main(args);
//Exercicio15.Main(args);
//Exercicio16.Main(args);
//Exercicio17.Main(args);
//Exercicio18.Main(args);
//Exercicio19.Main(args);
Exercicio20.Main(args);